In [16]:
import torch
t2=torch.tensor([[0,1,2],[3,4,5]])
print(t2)
print(t2.reshape(3,2)) #先打平，按一行逐渐排列
print(t2+1)#逐个元素计算
print('数据={}'.format(t2))
print('大小={}'.format(t2.size()))#显示维度信息具体长度
print('维度={}'.format(t2.dim()))
print('元素个数={}'.format(t2.numel()))
print('元素类型={}'.format(t2.dtype))

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[1, 2, 3],
        [4, 5, 6]])
数据=tensor([[0, 1, 2],
        [3, 4, 5]])
大小=torch.Size([2, 3])
维度=2
元素个数=6
元素类型=torch.int64
