In [1]:
import torch
t0=torch.tensor(0)
t1=torch.tensor([0,1,2,3])
t2=torch.tensor([[0,1,2],[2,3,4],[5,6,9]])
t3=torch.tensor([[[0,1,2],[2,3,4],[5,6,9]],
               [[0,1,2],[2,3,4],[5,6,9]],
               [[0,1,2],[2,3,4],[5,6,9]]])
print(t0)
print(t1)
print(t2)
print(t3)

tensor(0)
tensor([0, 1, 2, 3])
tensor([[0, 1, 2],
        [2, 3, 4],
        [5, 6, 9]])
tensor([[[0, 1, 2],
         [2, 3, 4],
         [5, 6, 9]],

        [[0, 1, 2],
         [2, 3, 4],
         [5, 6, 9]],

        [[0, 1, 2],
         [2, 3, 4],
         [5, 6, 9]]])
