In [5]:
import torch
t1=torch.empty(3) #构造出来的元素值是不确定的
print(t1)
t2=torch.zeros(2,2) #每个元素值为0
print(t2)
t3=torch.ones(4,3) #每个元素值为1
print(t3)
t4=torch.full([3,2],2.) #每个元素值为指定的元素
print(t4)

tensor([       nan, 2.3694e-38, 5.6052e-45])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [13]:
#构造类似的矩阵
a1=torch.empty_like(t1)
print(a1)
a2=torch.zeros_like(t2)
print(a2)
a3=torch.ones_like(t3)
print(a3)
a4=torch.full_like(t4,8)
print(a4)

tensor([0., 0., 0.])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[8., 8.],
        [8., 8.],
        [8., 8.]])
