In [8]:
import torch
#构造等差数列
a=torch.arange(0,4,1) #（end-start）/step 不包含末尾
print(a)
b=torch.range(0,3,1) #(end-start)/step+1
print(b)
c=torch.linspace(0,3,4) #step说明一共数列几个数 
print(c)
d=torch.logspace(0,3,4) 
d

tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.])


C:\Users\lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """


tensor([   1.,   10.,  100., 1000.])