In [1]:
import torch
a=torch.full([3,4],0.6)
print(a)
print(torch.bernoulli(a)) #生成大小为（3,4）的0-1的随机张量

tensor([[0.6000, 0.6000, 0.6000, 0.6000],
        [0.6000, 0.6000, 0.6000, 0.6000],
        [0.6000, 0.6000, 0.6000, 0.6000]])
tensor([[1., 1., 0., 0.],
        [0., 1., 0., 1.],
        [1., 0., 0., 1.]])


In [2]:
import torch
weights=torch.tensor([[1,100],[100,1],[1,1]],dtype=torch.float32)
print(torch.multinomial(weights,1))

tensor([[1],
        [0],
        [1]])


In [4]:
torch.randperm(10,dtype=torch.float32) #0-9 随机种子

tensor([0., 1., 4., 9., 6., 8., 2., 7., 3., 5.])

In [7]:
torch.randint(low=0,high=4,size=(3,4))

tensor([[0, 0, 3, 1],
        [1, 1, 0, 3],
        [0, 1, 2, 2]])

In [6]:
torch.randint_like(torch.ones(3,4),low=0,high=4)

tensor([[2., 3., 0., 1.],
        [2., 1., 0., 3.],
        [0., 1., 3., 3.]])

In [8]:
torch.rand(2,3)#构造标准均匀分布的的随机变量

tensor([[0.6676, 0.3867, 0.1494],
        [0.4140, 0.1789, 0.5087]])

In [9]:
torch.rand_like(torch.ones(3,3))

tensor([[0.9708, 0.8979, 0.4619],
        [0.0735, 0.8535, 0.2701],
        [0.6391, 0.2905, 0.2121]])

In [10]:
torch.randn(2,3) #构造标准正态分布的随机变量

tensor([[-1.8676, -0.0410,  0.0397],
        [ 0.8711, -1.9639,  0.7261]])

In [11]:
torch.randn_like(torch.ones(3,4))

tensor([[-0.6848, -1.2871, -1.0713, -0.1043],
        [ 0.4887,  0.8751,  0.2125, -1.3390],
        [-0.2753,  0.3103,  0.3310, -0.5979]])

In [13]:
#构造可以指定均值和方差的正态分布
mean=torch.tensor([0.,1.])
std=torch.tensor([3.,2.])
print(torch.normal(mean,std))

tensor([-1.3627,  3.1506])
