In [1]:
import torch
a=torch.arange(12)
print(a)
print(a.shape)
a1=a.reshape(3,2,2)#不改变元素的个数和各元素的值改变张量的大小 （size）
print(a1)
print(a1.shape)
a2=a.reshape(2,6)
print(a2)
print(a2.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])
torch.Size([3, 2, 2])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])


In [2]:
torch.arange(24).reshape(3,-1,4).shape #-1代替维度的大小，则该函数会根据张量元素个数自动计算出

torch.Size([3, 2, 4])

In [3]:
torch.arange(24).reshape(2,1,3,1,4).squeeze().shape #squeeze 可以消除丈量大小中为1的维度

torch.Size([2, 3, 4])

In [4]:
t=torch.rand(2,3,4)
t.unsqueeze(2).shape #增加大小为0的维度再指定的索引前面

torch.Size([2, 3, 1, 4])

In [5]:
t=torch.rand(3,4,5)
t.permute(2,1,0).shape #索引的位置为新维度 交换维度

torch.Size([5, 4, 3])

In [8]:
t1=torch.tensor([[1,2]])
print(t1.shape)
t2=t1.transpose(0,1) #将0维度和1维度进行交换
print(t2.shape)
t3=t2.t()
t3.shape

torch.Size([1, 2])
torch.Size([2, 1])


torch.Size([1, 2])